# Generated by Django 3.0.4 on 2020-03-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20200323_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='content',
            field=models.CharField(blank=True, help_text='如果设置的不是html类型，可为空', max_length=200, verbose_name='内容'),
        ),
    ]
